### ISSUE TITLE
Unable to load PKCS7 object error

### ISSUE THREAD

**Issue by vladoski** [Slamdunk/php-p7m-reader#3]
Hi, I'm trying to use your package to decode a p7m file to extract its content (an XML). The code that I've used is the same that you put in your README.  

The package gives me this error when I'm trying to decode the p7m:
```
PHP Fatal error:  Uncaught Slam\P7MReader\P7MReaderException: unable to load PKCS7 object
140258099995968:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:../crypto/asn1/tasn_dec.c:1130:
140258099995968:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:../crypto/asn1/tasn_dec.c:290:Type=PKCS7
 in /home/vlado/Projects/p7m-decode/vendor/slam/php-p7m-reader/lib/P7MReader.php:76
Stack trace:
#0 /home/vlado/Projects/p7m-decode/vendor/slam/php-p7m-reader/lib/P7MReader.php(50): Slam\P7MReader\P7MReader::exec()
#1 /home/vlado/Projects/p7m-decode/foo.php(6): Slam\P7MReader\P7MReader::decodeFromFile()
#2 {main}
      thrown in /home/vlado/Projects/p7m-decode/vendor/slam/php-p7m-reader/lib/P7MReader.php on line 76
```
I really have to say that I'm trying to find a package, module or method that can extract the XML from this one client that gives me an headache. I've found a bash script that decodes it correctly but I can't find anything that works in PHP.  

Thanks,  
Vlad

**Comment by Slamdunk** [comment]
Can you paste here the working bash script?

**Comment by vladoski** [comment]
Here you can find it: https://github.com/eniocarboni/p7m
